### PR TITLE
Change filename to be a positional argument

### PR DESCRIPTION
**Pull request by Ben1152000**
This PR contains the following changes:

- Change filename to a positional argument (`sootty filename.vcd` instead of `sootty -f filename.vcd`)
- Replace `-d` display argument with `-o` output (which does the opposite)
- Fix minor bugs/clean up code in save.py

### CODE REVIEW

**Comment by KarthikL1729** [comment]
Looks good to me, fixed a small bug in the reloading part, functionality wise it's perfect. Also really like the new dict representation in the save file!

**Comment by KarthikL1729** [comment]
Pushed the fix and tested functionality, would like your opinion on the date format!

**Comment by Ben1152000** [comment]
> However I do think the old date format would be preferred for most usecases?

I went with the unix timestamp since it's very easy to compare two values. I'm not sure if there are any weird issues when comparing dates, but if you think it's better to have readability feel free to change it.

> I also think providing absolute path would be better as that would allow us to reload from anywhere in the directory tree, will push a fix for that.

Agreed, this behavior seems more reasonable.

**Review by yihuajack — APPROVED** [review]
Looks good to me. The changes are reasonable.

**Comment by KarthikL1729** [comment]
> > However I do think the old date format would be preferred for most usecases?
> 
> I went with the unix timestamp since it's very easy to compare two values. I'm not sure if there are any weird issues when comparing dates, but if you think it's better to have readability feel free to change it.
> 
> > I also think providing absolute path would be better as that would allow us to reload from anywhere in the directory tree, will push a fix for that.
> 
> Agreed, this behavior seems more reasonable.

I think the unix timestamp is fine as well, not an issue per se. Will solve conflicts and approve.

**Review by KarthikL1729 — APPROVED** [review]

**Pull request merged**
