### PR TITLE
Added modules for AND, OR and NOT, need to debug a few cases

### PR DESCRIPTION
**Pull request by KarthikL1729**
Modules added, should be able to replicate the issue faced.

### CODE REVIEW

**Review by Ben1152000 — CHANGES_REQUESTED** [review]
Overall it looks good, one small change I would make before merging is to add documentation to the `grammar.md` file with the new query language syntax. Once that's done I'll approve the PR.

**Comment by KarthikL1729** [comment]
> Overall it looks good, one small change I would make before merging is to add documentation to the `grammar.md` file with the new query language syntax. Once that's done I'll approve the PR.

Will do

**Comment by KarthikL1729** [comment]
Done, please check

**Review by Ben1152000 — APPROVED** [review]
Looks good! I would also add unary operators and parentheses to the front of the precedence list. Once you do that feel free to merge.

**Comment by KarthikL1729** [comment]
Just added them, merging now.

**Pull request merged**
